# coding: utf-8

"""
    Wise Platform API

    Comprehensive API for Wise platform services including: - Profile - Activity tracking and management - Quote creation and management - Recipient - Transfer 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wise_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_business_profile(self) -> None:
        """Test case for create_business_profile

        Create a business profile
        """
        pass

    def test_create_personal_profile(self) -> None:
        """Test case for create_personal_profile

        Create a personal profile
        """
        pass

    def test_profiles_profile_id_quotes_post(self) -> None:
        """Test case for profiles_profile_id_quotes_post

        Create an authenticated quote
        """
        pass

    def test_profiles_profile_id_quotes_quote_id_get(self) -> None:
        """Test case for profiles_profile_id_quotes_quote_id_get

        Retrieve a quote by ID
        """
        pass

    def test_profiles_profile_id_quotes_quote_id_patch(self) -> None:
        """Test case for profiles_profile_id_quotes_quote_id_patch

        Update a quote
        """
        pass

    def test_quotes_post(self) -> None:
        """Test case for quotes_post

        Create an unauthenticated quote
        """
        pass

    def test_v1_accounts_post(self) -> None:
        """Test case for v1_accounts_post

        Create a recipient account
        """
        pass

    def test_v1_profiles_profile_id_directors_get(self) -> None:
        """Test case for v1_profiles_profile_id_directors_get

        List directors
        """
        pass

    def test_v1_profiles_profile_id_directors_post(self) -> None:
        """Test case for v1_profiles_profile_id_directors_post

        Add directors
        """
        pass

    def test_v1_profiles_profile_id_directors_put(self) -> None:
        """Test case for v1_profiles_profile_id_directors_put

        Update directors
        """
        pass

    def test_v1_profiles_profile_id_partner_licence_transfers_post(self) -> None:
        """Test case for v1_profiles_profile_id_partner_licence_transfers_post

        Create partner license transfer
        """
        pass

    def test_v1_profiles_profile_id_verification_documents_post(self) -> None:
        """Test case for v1_profiles_profile_id_verification_documents_post

        Create identification document
        """
        pass

    def test_v1_quotes_quote_id_account_requirements_get(self) -> None:
        """Test case for v1_quotes_quote_id_account_requirements_get

        Get account requirements for a quote
        """
        pass

    def test_v1_refund_accounts_post(self) -> None:
        """Test case for v1_refund_accounts_post

        Create a refund recipient account
        """
        pass

    def test_v1_transfer_requirements_post(self) -> None:
        """Test case for v1_transfer_requirements_post

        Get transfer requirements
        """
        pass

    def test_v1_transfers_get(self) -> None:
        """Test case for v1_transfers_get

        List transfers
        """
        pass

    def test_v1_transfers_post(self) -> None:
        """Test case for v1_transfers_post

        Create a standard transfer
        """
        pass

    def test_v1_transfers_transfer_id_documents_noc_get(self) -> None:
        """Test case for v1_transfers_transfer_id_documents_noc_get

        Get NOC document
        """
        pass

    def test_v1_transfers_transfer_id_get(self) -> None:
        """Test case for v1_transfers_transfer_id_get

        Get transfer by ID
        """
        pass

    def test_v1_transfers_transfer_id_invoices_bankingpartner_get(self) -> None:
        """Test case for v1_transfers_transfer_id_invoices_bankingpartner_get

        Get banking partner invoice (v1)
        """
        pass

    def test_v1_transfers_transfer_id_payments_get(self) -> None:
        """Test case for v1_transfers_transfer_id_payments_get

        List transfer payments
        """
        pass

    def test_v1_transfers_transfer_id_put(self) -> None:
        """Test case for v1_transfers_transfer_id_put

        Cancel transfer
        """
        pass

    def test_v1_transfers_transfer_id_receipt_pdf_get(self) -> None:
        """Test case for v1_transfers_transfer_id_receipt_pdf_get

        Get transfer receipt PDF
        """
        pass

    def test_v2_accounts_account_id_delete(self) -> None:
        """Test case for v2_accounts_account_id_delete

        Deactivate a recipient account
        """
        pass

    def test_v2_accounts_account_id_get(self) -> None:
        """Test case for v2_accounts_account_id_get

        Get recipient account by ID
        """
        pass

    def test_v2_accounts_get(self) -> None:
        """Test case for v2_accounts_get

        List recipient accounts
        """
        pass

    def test_v2_profiles_get(self) -> None:
        """Test case for v2_profiles_get

        List profiles for a user account
        """
        pass

    def test_v2_profiles_profile_id_business_profile_put(self) -> None:
        """Test case for v2_profiles_profile_id_business_profile_put

        Update a business profile
        """
        pass

    def test_v2_profiles_profile_id_get(self) -> None:
        """Test case for v2_profiles_profile_id_get

        Retrieve a profile by ID
        """
        pass

    def test_v2_profiles_profile_id_personal_profile_put(self) -> None:
        """Test case for v2_profiles_profile_id_personal_profile_put

        Update a personal profile
        """
        pass

    def test_v2_profiles_profile_id_third_party_transfers_post(self) -> None:
        """Test case for v2_profiles_profile_id_third_party_transfers_post

        Create third-party transfer
        """
        pass

    def test_v2_profiles_profile_id_third_party_transfers_transfer_id_get(self) -> None:
        """Test case for v2_profiles_profile_id_third_party_transfers_transfer_id_get

        Get third-party transfer
        """
        pass

    def test_v2_transfers_transfer_id_invoices_bankingpartner_get(self) -> None:
        """Test case for v2_transfers_transfer_id_invoices_bankingpartner_get

        Get banking partner invoice (v2)
        """
        pass

    def test_v3_profiles_profile_id_transfers_transfer_id_payments_post(self) -> None:
        """Test case for v3_profiles_profile_id_transfers_transfer_id_payments_post

        Fund a transfer
        """
        pass

    def test_v3_profiles_profile_id_verification_status_bank_transfer_post(self) -> None:
        """Test case for v3_profiles_profile_id_verification_status_bank_transfer_post

        Check verification status
        """
        pass


if __name__ == '__main__':
    unittest.main()
